"""backtest trade signal price

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-01 17:39:38.653320
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_trades", sa.Column("signal_price", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtest_trades", "signal_price")
    # ### end Alembic commands ###
